blank_issues_enabled: false
contact_links:
    - name: âœ¨ Feature Request
      url: https://github.com/presidio-oss/hai-build-codegen/discussions/categories/feature-requests?discussions_q=is%3Aopen+category%3A%22Feature+Requests%22+sort%3Atop
      about: Share and vote on feature requests for HAI